version: '3.8'
services:
  gateway:
    build: gateway/
    container_name: shareit_gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      # - TZ=Europe/Moscow
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server/
    container_name: shareit_server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      # - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share-it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  db:
    image: postgres:13.7-alpine
    container_name: shareit_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share-it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin